basic_app/urls.py
from django.urls import path, include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

learn_usr/urls.py
from django.contrib import admin
from basic_app import views

from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)

    # additionl
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse

# Login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def other(request):
    return render(request, 'basic_app/other.html')

#@login_required
def relative(request):
    return render(request, 'basic_app/relative.html')

@login_required
def special(request):
    return HttpResponse('You are logged in!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('inputPassword')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Accound not active')
        else:
            print('Someone tried to login and failed')
            print(f'usr: {username}, and pass: {password} ')
            return HttpResponse('Invalid login details supplied!')

    else:
        return render(request,'basic_app/login.html',{})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>
  <body>
    <h1>Welcome to base</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Costum bar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Relative pages
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Go to admin_page</a></li>
                <li><a class="dropdown-item" href="{% url 'basic_app:relative' %}">Go to relative page</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'basic_app:register' %}">Register</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          {% if user.is_authenticated %}
          <ul class="nav justify-content-end nav-pills">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
          {% else %}
          <ul class="nav justify-content-end nav-pills">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'basic_app:user_login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'basic_app:register' %}">Register</a>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <script>
    src="http://code.jquery.com/jquery-3.1.1.js"
    integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
    crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
  <style>
    body{
      background-image: url("static/PDk2Vs.jpg");
      background-repeat: no-repeat;
        }
  </style>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is index page</h2>
  {% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

  {% block body_block %}

  <h1> Please Login </h1>

  <form class="" action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3 row">
      <label for="username" class="col-sm-2 col-form-label">Username:</label>
      <div class="col-sm-10">
        <input class="form-control form-control-lg" type="text" placeholder="your username" aria-label=".form-control-lg example" name="username">
      </div>
    </div>
    <div class="mb-3 row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Password:</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" name="inputPassword">
      </div>
    </div>
    <input type="submit" name="" value="Login">
  </form>
  {% endblock %}

templates/basic_app/other.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to other page!</h1>
    <h2>Example</h2>
  {% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
  <div class="container">
      {% if registered %}
        <h1> Thank you for registering!</h1>
      {% else %}
        <h1>Register here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype='multipart/form-data' method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
  </div>

{% endblock %}

templates/basic_app/relative.html
{% extends 'basic_app/base.html' %}